config/routes.rb
Zhule::Application.routes.draw do

  root :to => 'index#index', :as => :root
  match 'sign_in' => 'index#index', :as => :sign_in
  match 'sign_up' => 'index#sign_up', :as => :sign_up, :via => [:get, :post]
  match 'sign_out' => 'index#sign_out', :as => :sign_out

  scope 'square' do
    match '/' => 'index#square', :as => :square
    match 'load_square_columns' => 'index#load_square_columns', :via => :get
  end
  
  # match 'square' => 'index#square', :as => :square
  match 'home' => 'home#index', :as => :home

  resources :users do
    member do
      post :follow
    end
  end

  resources :dialogs do
    collection do
      post :send_message
    end

    # member do
    #   post :read_messages
    # end
  end

  resources :assistances, :except => [:index] do
    member do
      get :joined
      post :join
    end

    collection do
      post :mark_as_helpful
      post :upload_photo
    end
  end

  resources :notifications, :only => [:index, :destroy]
  resources :comments, :only => [:create, :destroy]  

  scope 'settings' do
    match '/' => 'settings#index', :as => :settings, :via => [:get, :post]
    match 'password' => 'settings#password', :as => :setting_password, :via => [:get, :post]
    match 'avatar' => 'settings#avatar', :as => :setting_avatar, :via => [:get, :post]
    match 'avatar/crop' => 'settings#crop_avatar', :as => :crop_avatar
  end

   match 'auth/weibo/callback' => 'auth#weibo_login'
   match 'auth/new_user' => 'auth#new_user', :as => :auth_new_user, :via => 'POST'
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/views/index/_square_cols.haml
- assistances.each do |assist|
  .col
    .pd
      .detail
        - unless assist.attachments.blank?
          .picture
            = image_tag assist.attachments.first.photo_url(:m)
        %p
          = assist.content
        .persons
          %a{ :href => assistance_path(assist.id) }
            = "#{assist.helpers_count} 人帮TA"            
    .user
      .avatar
        %a{ :href => user_path(assist.user_id), :rel => 'tipsy', :title => assist.user.login }
          = image_tag assist.user.avatar_url(:s)
      .remarks
        %a{ :href => user_path(assist.user_id), :rel => 'tipsy', :title => assist.user.login  }= assist.user.login
        在
        %abbr.timeago{ :title => assist.created_at }
        发起

app/views/index/index.haml
- content_for :header_js do
  = javascript_include_tag 'sign'
- content_for :meta do
  %meta{ :property => 'wb:webmaster', :content => '48047f650fd5b12e' }
  
.container
  .recommands
    .aboutzl
      %p
        %span 助乐
        是一个基于互相帮助的小微社区，你可以在这里尝试把你的愿望，困难或者想法说出来让大家一起帮你，或者你也可以使用你的能力和爱心，
        去帮助需要帮助的人，同时获得快乐。
    - @assistances.each do |assistance|
      .recommand
        .avatar
          = image_tag assistance.user.avatar_url(:m), :size => '80x80'
          / .addr
          /   广东 广州
        .seekhelp
          
          %p.detail{ :title => assistance.content }
            %a.user_name{ :href => user_path(assistance.user_id) }= "#{assistance.user.login}:" 
            = assistance.content.truncate(100)
          - if assistance.attachments.first.present?
            .photo
              = image_tag assistance.attachments.first.photo_url(:m)
        .tools
          %a.button{ :href => assistance_path(assistance.id) } 去帮TA
          
  .weibo_login
    %a{ :href => '/auth/weibo' }
      = image_tag 'weibo240.png'   

  .login-form
    = form_tag sign_in_path, :id => 'loginForm' do
      %p.register
        / %a.big_button 立即注册
        有 26 个人正在寻求帮助，快去帮帮TA吧！
      .login
        %p.error
          = flash[:error]
        %p
          %input.text.email{ :type => 'text', :name => 'email', :value => '输入你的注册邮箱', :init_text => '输入你的注册邮箱' }
        %p
          %input.text.password_init{ :type => 'text', :value => '输入你的登录密码' }
          %input.text.password{ :type => 'password', :style => 'display:none;', :name => 'password' }
        %p
          %a.button.submit{ :href => 'javascript:;' } 登录
          %a.button.green{ :href => sign_up_path } 注册
        %p
          %a.forget_password{ :href => '#' } 忘记密码？

app/views/index/sign_up.haml
- content_for :header_js do
  = javascript_include_tag 'sign'

.container
  .left_form
    .sign_up_form
      .notify
        注册助乐网
      = form_tag sign_up_path, :id => 'newUserForm' do
        .form_panel
          = render 'shared/flash_notice'
          .blank
            %span.attr 邮箱：
            %input.text{ :type => 'text', :name => 'user[email]' }
            %span.message 输入你的邮箱
          .blank
            %span.attr 昵称：
            %input.text{ :type => 'text', :name => 'user[login]' }
            %span.message 输入你想要的昵称
          .blank
            %span.attr 密码：
            %input.text{ :type => 'password', :name => 'user[password]' }
            %span.message 输入安全的密码
          .blank
            %span.attr 确认密码：
            %input.text{ :type => 'password', :name => 'user[password_confirmation]' }
            %span.message 再输入一遍密码
          .buttons
            %a.button.submit{ :href => 'javascript:;' } 提交注册

  .right_reminder
    .authlogin     
      .title
        或者使用以下方式登录
      .logways
        %p
          %a{ :href => '/auth/weibo' }
            = image_tag 'weibo240.png'

    .signed_up     
      .title
        已经有账号了？
      .links
        %p
          %a{ :href => sign_in_path } 登录
        %p
          %a{ :href => '#' } 忘记密码        

app/views/index/square.haml
- content_for :header_css do
  = stylesheet_link_tag 'square'

- content_for :header_js do
  = javascript_include_tag 'square'  

.container
  .square_waterfall.clearfix
    .result_col.col_0
    .result_col.col_1
    .result_col.col_2
    .result_col.col_3
              
                