config/routes.rb
Zhule::Application.routes.draw do

  root :to => 'index#index', :as => :root
  match 'sign_in' => 'index#index', :as => :sign_in
  match 'sign_up' => 'index#sign_up', :as => :sign_up, :via => [:get, :post]
  match 'sign_out' => 'index#sign_out', :as => :sign_out

  scope 'square' do
    match '/' => 'index#square', :as => :square
    match 'load_square_columns' => 'index#load_square_columns', :via => :get
  end
  
  # match 'square' => 'index#square', :as => :square
  match 'home' => 'home#index', :as => :home

  resources :users do
    member do
      post :follow
    end
  end

  resources :dialogs do
    collection do
      post :send_message
    end

    # member do
    #   post :read_messages
    # end
  end

  resources :assistances, :except => [:index] do
    member do
      get :joined
      post :join
    end

    collection do
      post :mark_as_helpful
      post :upload_photo
    end
  end

  resources :notifications, :only => [:index, :destroy]
  resources :comments, :only => [:create, :destroy]  

  scope 'settings' do
    match '/' => 'settings#index', :as => :settings, :via => [:get, :post]
    match 'password' => 'settings#password', :as => :setting_password, :via => [:get, :post]
    match 'avatar' => 'settings#avatar', :as => :setting_avatar, :via => [:get, :post]
    match 'avatar/crop' => 'settings#crop_avatar', :as => :crop_avatar
  end

   match 'auth/weibo/callback' => 'auth#weibo_login'
   match 'auth/new_user' => 'auth#new_user', :as => :auth_new_user, :via => 'POST'
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/assistance.rb
# coding: utf-8
class Assistance
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::CounterCache

  field :title
  field :content
  field :address, :type => String, :default => ''
  field :assist_public, :type => Boolean, :default => true
  field :pictures, :type => Array, :default => []
  field :solved, :type => Boolean, :default => false

  field :helpers_count, :type => Integer, :default => 0
  field :comments_count, :type => Integer, :default => 0
  
  validates_presence_of :content

  belongs_to :user, :inverse_of => :assistances
  counter_cache :name => :user, :inverse_of => :assistances

  index :user_id => 1

  has_many :assistance_helpers
  has_many :comments, :as => :commentable
  has_many :attachments, :as => :attachmentable

  default_scope desc(:created_at)


end

app/models/assistance_helper.rb
# coding: utf-8
class AssistanceHelper
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::CounterCache
  include Mongoid::DelayedDocument

  field :helpful, :type => Boolean, :default => false
  field :content

  belongs_to :user
  counter_cache :name => :user, :inverse_of => :helped_stuffs

  belongs_to :assistance
  counter_cache :name => :assistance, :inverse_of => :helpers

  validates_uniqueness_of :user_id, :scope => :assistance_id

  scope :helpful_assistance, where(:helpful => true).desc('created_at updated_at')

  index :user_id => 1
  index :assistance_id => 1
  index :helpful => 1

  def assistance_user
    
  end

  before_create do
    return false if self.user_id == self.assistance.user_id
  end

  after_create do
    self.class.perform_async(:send_join_notification, self._id)
  end

  after_save do
    if self.helpful
      self.class.perform_async(:send_assist_notification, self._id)
    end
  end

  def self.send_join_notification(assistance_helper_id)
    assistance_helper = AssistanceHelper.where(:_id => assistance_helper_id).first
    Notification::JoinAssistance.create :user_id                 => assistance_helper.assistance.user_id, 
                                        :assistance_id           => assistance_helper.assistance_id,
                                        :assistance_helper_id    => assistance_helper._id    
  end

  def self.send_assist_notification(assistance_helper_id)
    assistance_helper = AssistanceHelper.where(:_id => assistance_helper_id).first
    Notification::Assist.create :user_id                 => assistance_helper.user_id, 
                                :assistance_id           => assistance_helper.assistance_id,
                                :assistance_helper_id    => assistance_helper._id       
  end

end

app/controllers/assistances_controller.rb
# coding: utf-8
class AssistancesController < ApplicationController
  layout 'assistance'
  before_filter :require_login, :except => [:show, :joined]
  skip_before_filter :verify_authenticity_token, :only => :upload_photo

  def new
    @user = current_user
    render :template => 'assistances/new_assistance_form', :layout => false
    # respond_to do |format|
    #   format.html { redirect_to home_path }
    #   format.js {
    #     render :template => 'assistances/new_assistance_form'
    #   }
    # end
  end

  def show
    @assist = Assistance.where(:_id => params[:id]).first
    @user = @assist.user
    set_seo_meta(@assist.content.truncate(50), nil, @assist.content)
    @assist_helpers = @assist.assistance_helpers.includes(:user).limit(20)
    @comments = @assist.comments.includes(:user).paginate(:page => params[:page], :per_page => 20)
  end

  def create
    @user = current_user
    begin
      assist = @user.assistances.build(:content => params[:content], :address => params[:address])
      if !params[:attachment_id].blank? && assist.save
        attachment = Attachment.where(:_id => params[:attachment_id]).first
        attachment.update_attributes(:attachmentable_type => 'Assistance', :attachmentable_id => assist.id)
      end
      respond_to do |format|
        format.js { render :text => { :success => assist.save, :id => assist._id }.to_json }
      end
    rescue
      render :text => { :success => false }.to_json
    end
  end

  def edit
    @assist = Assistance.where(:_id => params[:id]).first
    @user = @assist.user
    return if current_user != @user
    @address = @assist.address
    @address = '地点' if @address.blank?
    @filename = '上传图片'
    @attachment = @assist.attachments.first
    @filename = @attachment.photo_filename if @attachment.present?
  end

  def update
  end

  def joined
    @assist = Assistance.where(:_id => params[:id]).first
    set_seo_meta(@assist.content.truncate(30), nil, @assist.content.truncate(30))
    @user = @assist.user
    @helpers = @assist.assistance_helpers.includes(:user)
  end

  def join
    assistance_helper = current_user.assistance_helpers.build(:assistance_id => params[:id], :content => params[:content])
    expire_fragment('newest_helps')
    respond_to do |format|
      format.js { render :text => { :success => assistance_helper.save }.to_json }
    end
  end

  def upload_photo
    photo = current_user.attachments.build(:photo => params[:photo])
    render :text => { :success => photo.save, :id => photo.id, :photo_name => params[:photo].original_filename }.to_json
  end

  def mark_as_helpful
    assistance_helper = AssistanceHelper.where(:_id => params[:id]).first
    assistance_helper.update_attribute(:helpful, true)
    render :nothing => true
  end
  
end

app/views/assistances/edit.haml
.eadit_assistance_detail
  .new_help_form
    .notice
      编辑求助内容
    .form_panel#newAssistance
      %textarea.form_text{ :name => 'content', 'data-attachment_id' => @attachment.id }= @assist.content
      .bottom_tools
        .option
          %a.location{ :href => 'javascript:;' }
            %i.icons.icons_c_map
            %span= @address
        .option     
          %a.uploadImage{ :href => 'javascript:;' }
            %i.icons.icons_img
            %span= @filename                  
      %a.button.green.submit{ :href => 'javascript:;' } 修改求助

  .attachment_panel.address{ :style => 'display:block;'}
    .title
      编辑地点
    .address_input
      %input.text{ :type => 'text', :value => @address }
      %a.button.submit{ :href => 'javascript:;' } 确定
      %a.button.gray{ :href => 'javascript:;' } 取消

  .attachment_panel.photo{ :style => 'display:block;'}
    .title
      上传图片
    .photo_input
      = form_tag upload_photo_assistances_path, :multipart => true do
        %input{ :type => 'file', :name => 'photo' }
        %a.button.submit{ :href => 'javascript:;' } 确定
        %a.button.gray{ :href => 'javascript:;' } 取消
    .current_photo
      - if @attachment.present?
        = image_tag @attachment.photo_url(:m)    

app/views/assistances/joined.haml
.assistance_detail
  .content
    = @assist.content
  .tools
    .status
      %abbr.timeago{ :title => @assist.created_at }
      %a{ :href => '#' }
        %i.icons.icons_map
        北京 朝阳
      %a{ :href => joined_assistance_path(@assist.id) }
        %i.icons.icons_person
        = "参与帮忙(#{@assist.helpers_count})"
      %a{ :href => assistance_path(@assist.id) }
        %i.icons.icons_comt
        = "评论(#{@assist.comments_count})"
      - if logged_in? && current_user == @assist.user
        %a{ :href => 'javascript:;' }
          %i.icons.icons_pencil
          编辑        
    .buttons
      - if logged_in? && current_user != @user
        %a.button.helpWhom{ :href => 'javascript:;', :class => current_user.helped?(@assist.id) ? 'gray' : '' }
          = current_user.helped?(@assist.id) ? '已提交帮助' : '帮她一把'

- if logged_in?
  .i_can_help    
    %textarea.form_text{ 'data-assistance_id' => @assist.id } 我能帮你：
    %a.button.submit{ :href => 'javascript:;', :class => current_user.helped?(@assist.id) ? 'gray' : '' } 发送

.participate
  .title
    这些人参与帮忙了
  .helper_list
    - if @helpers.blank?
      %p{ :style => 'color: #999999;', :align => 'center' } 暂时还没有人帮TA...
    - else
      - @helpers.each do |help|
        .helper_single_line
          .avatar
            %a{ :href => user_path(help.user_id) }
              = image_tag help.user.avatar_url(:c), :size => '50x50'
          .info
            %p
              - if logged_in? && help.user_id != current_user.id
                = message_link_tag(help.user)              
              %a.user_name{ :href => user_path(help.user_id) }= "#{help.user.login}:"
              = help.content          
            .bottom_tools
              .status
                %abbr.timeago{ :title => help.created_at }
              - if logged_in? && current_user.id == @assist.user_id
                .buttons
                  %a.button.green.markAsHelpful{ :href => 'javascript:;', 'data-help_id' => help.id, :class => help.helpful ? 'gray' : '' } 对我有用

app/views/assistances/show.haml
.assistance_detail
  .content
    = @assist.content
    .pics
      - unless @assist.attachments.blank?
        - @assist.attachments.each do |attach|
          = image_tag attach.photo_url(:m), 'data-large_url' => attach.photo_url(:l), :class => 'small'

  .tools
    .status
      %abbr.timeago{ :title => @assist.created_at }
      - if @assist.address.present?
        %a{ :title => @assist.address }
          %i.icons.icons_map
          = @assist.address
      %a{ :href => joined_assistance_path(@assist.id) }
        %i.icons.icons_person
        = "参与帮忙(#{@assist.helpers_count})"
      %a{ :href => assistance_path(@assist.id) }
        %i.icons.icons_comt
        = "评论(#{@assist.comments_count})"
      - if logged_in? && current_user == @assist.user        
        %a{ :href => '#' }
          %i.icons.icons_pencil
          编辑        
    .buttons
      - if logged_in? && current_user != @user
        %a.button.helpWhom{ :href => 'javascript:;', :class => current_user.helped?(@assist.id) ? 'gray' : '' }
          = current_user.helped?(@assist.id) ? '已提交帮助' : '帮她一把'
- if logged_in?
  .i_can_help    
    %textarea.form_text{ 'data-assistance_id' => @assist.id } 我能帮你：
    %a.button.submit{ :href => 'javascript:;', :class => current_user.helped?(@assist.id) ? 'gray' : '' } 发送

.participate
  .title
    这些人帮了TA
    %a.action{ :href => joined_assistance_path(@assist.id) } 更多
  .helper_list
    - if @assist_helpers.blank?
      %p{ :style => 'margin: 10px auto; color: #999' } 
        暂时还没有人帮TA...      
    - else
      - @assist_helpers.each do |assist_helper|
        .helper_li
          %a{ :href => user_path(assist_helper.user_id), :title => assist_helper.helpful ? "对#{@user.login}有帮助的" : assist_helper.user.login, :rel => 'tipsy' }
            = image_tag assist_helper.user.avatar_url(:c), :size => '50x50'
          - if assist_helper.helpful
            %i.icons.icons_smile


.comment_panel
  .title
    评论
    %a.action 发表
  .comt_list
    - if @comments.blank?
      %p{ :style => 'margin:10px 10px;' } 暂时没有任何评论...
    - else
      = render :partial => 'comments/comment', :collection => @comments
  = will_paginate @comments, :class => 'digg_pagination'
  - if logged_in?
    .new_comt_form
      %textarea.form_text
      %a.button.postComment{ :href => 'javascript:;', 'data-commentable_id' => @assist.id, 'data-commentable_type' => 'Assistance' } 评论