config/routes.rb
Zhule::Application.routes.draw do

  root :to => 'index#index', :as => :root
  match 'sign_in' => 'index#index', :as => :sign_in
  match 'sign_up' => 'index#sign_up', :as => :sign_up, :via => [:get, :post]
  match 'sign_out' => 'index#sign_out', :as => :sign_out

  scope 'square' do
    match '/' => 'index#square', :as => :square
    match 'load_square_columns' => 'index#load_square_columns', :via => :get
  end
  
  # match 'square' => 'index#square', :as => :square
  match 'home' => 'home#index', :as => :home

  resources :users do
    member do
      post :follow
    end
  end

  resources :dialogs do
    collection do
      post :send_message
    end

    # member do
    #   post :read_messages
    # end
  end

  resources :assistances, :except => [:index] do
    member do
      get :joined
      post :join
    end

    collection do
      post :mark_as_helpful
      post :upload_photo
    end
  end

  resources :notifications, :only => [:index, :destroy]
  resources :comments, :only => [:create, :destroy]  

  scope 'settings' do
    match '/' => 'settings#index', :as => :settings, :via => [:get, :post]
    match 'password' => 'settings#password', :as => :setting_password, :via => [:get, :post]
    match 'avatar' => 'settings#avatar', :as => :setting_avatar, :via => [:get, :post]
    match 'avatar/crop' => 'settings#crop_avatar', :as => :crop_avatar
  end

   match 'auth/weibo/callback' => 'auth#weibo_login'
   match 'auth/new_user' => 'auth#new_user', :as => :auth_new_user, :via => 'POST'
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/setting.rb
class Setting < Settingslogic
  source "#{Rails.root}/config/config.yml"
  namespace Rails.env
end

app/controllers/settings_controller.rb
# coding: utf-8
class SettingsController < ApplicationController
  layout 'setting'
  before_filter :require_login
  before_filter :set_meta_tag

  def index
    if request.post?
      current_user.login = params[:login]
      current_user.address = params[:address]
      current_user.tag_list = params[:tag_list]
      current_user.tagline = params[:tagline]
      current_user.open_page = params[:open_page]
      if current_user.save
        flash[:success] = '资料更新成功'
      else
        flash[:error] = current_user.errors.full_messages
      end
      redirect_to :back
    end
  end

  def password
    if request.post?
      if current_user.password == params[:current_password]
        current_user.password = params[:new_password]
        current_user.password_confirmation = params[:new_password_confirmation]
        if current_user.save
          flash[:success] = '密码修改成功'
        else
          flash[:error] = current_user.errors.full_messages
        end
      else
        flash[:error] = ['当前密码输入错误']
      end
      redirect_to :back
    end
  end

  def avatar
    if request.post?
      redirect_to :back and return if params[:avatar].blank?
      current_user.avatar = params[:avatar]
      current_avatar_path = File.join(Rails.root, 'public', current_user.avatar.url)
      image = MiniMagick::Image.open(current_avatar_path)    
      
      if image[:width] < 180 || image[:height] < 180
        flash[:error] = current_user.errors.full_messages unless current_user.save
        redirect_to :back
      else
        render :template => 'settings/crop_avatar'
      end
    end
  end

  def crop_avatar
    if request.post?
      begin
        current_avatar_path = File.join(Rails.root, 'public', params[:last_upload_avatar])
        x, y, w, h = params[:crop_position].split(',')
        image = MiniMagick::Image.open(current_avatar_path)
        image.crop("#{w}x#{h}+#{x}+#{y}!")
        image.coalesce(current_avatar_path, current_avatar_path) if image.mime_type == 'image/gif'
        current_user.avatar = image
        current_user.save
      rescue => e
        logger.error e
      end
      redirect_to setting_avatar_path
    end
  end

  private 

  def set_meta_tag
    set_seo_meta("#{current_user.login}-设置")
  end

end

app/views/settings/avatar.haml
.edit_avatar_form_panel
  = render 'shared/flash_notice'
  .current_avatar
    .div-name
      当前头像
    .avatar_img
      = image_tag current_user.avatar.url(:l), :size => '180x180'
  .upload_avatar
    = form_tag setting_avatar_path, :multipart => true, :id => 'settingForm' do
      .div-name
        上传新头像
      .upload
        %input{ :type => 'file', :name => 'avatar' }
        .buttons
          %a.button.submit{ :href => 'javascript:;' } 上传头像

app/views/settings/crop_avatar.haml
- content_for :header_js do
  = javascript_include_tag 'lib/jcrop/jquery.Jcrop.min'
- content_for :header_css do  
  = stylesheet_link_tag 'lib/jcrop/css/jquery.Jcrop.min'

.crop_avatar_form_panel
  = render 'shared/flash_notice'
  .current_avatar
    .div-name
      拖动选择框以选择截取范围
    .avatar_img
      = image_tag current_user.avatar.url, :id => 'cropImage'
  .crop_avatar
    = form_tag crop_avatar_path, :id => 'settingForm' do
      .div-name
        预览
      .preview_panel{ :style => 'width:180px; height:180px; overflow:hidden;' }
        = image_tag current_user.avatar.url, :id => 'previewImage'
        = text_field_tag 'crop_position'
        = text_field_tag 'last_upload_avatar', current_user.avatar.url
      .buttons
        %a.button.submit{ :href => 'javascript:;' } 确定
        %a.button.gray{ :href => setting_avatar_path } 取消

:javascript
  var jcrop_api, boundx, boundy;
  $('#cropImage').Jcrop({
    onChange : updatePreview,
    onSelect : updatePreview,
    aspectRatio : 1,
    minSize : [180, 180],
    maxSize : [300, 300],
    bgFade : true,
    setSelect : [54, 37, 180, 180]
    }, function(){
      var bounds = this.getBounds();
      boundx = bounds[0];
      boundy = bounds[1];
      jcrop_api = this;
  });

  function updatePreview (c) {
    var rx = 180 / c.w, ry = 180 / c.h;
    $('#previewImage').css({
      width : Math.round(rx * boundx) + 'px',
      height : Math.round(ry * boundy) + 'px',
      marginLeft: '-' + Math.round(rx * c.x) + 'px',
      marginTop: '-' + Math.round(ry * c.y) + 'px'
    });
    var crop_position = [c.x, c.y, c.w, c.h];
    $('#crop_position').val(crop_position);     
  };  

app/views/settings/index.haml
.edit_info_form_panel
  = render 'shared/flash_notice'
  = form_tag settings_path, :id => 'settingForm' do
    .blank
      %span.attr 邮箱：
      %input.text.disabled{ :type => 'text', :disabled => true, :value => current_user.email }
      %span.message 你当前的邮箱
    .blank
      %span.attr 昵称：
      %input.text{ :type => 'text', :name => 'login', :value => current_user.login }
      %span.message 你的昵称
    .blank
      %span.attr 地区：
      %input.text{ :type => 'text', :name => 'address', :value => current_user.address }
      %span.message 你所在的地区
      

    .blank
      %span.attr 主页地址：
      %input.text{ :type => 'text', :name => 'open_page', :value => current_user.open_page }
      %span.message 如：http://weibo.com/huangjin2011

    .blank
      %span.attr 擅长于：
      %textarea.form_text{ :type => 'text', :name => 'tag_list' }= current_user.tag_list
      %span.message 形如 ‘计算机，旅游’，用 ',' 隔开
    .blank
      %span.attr 个人签名：
      %textarea.form_text{ :type => 'text', :name => 'tagline' }= current_user.tagline

    .buttons
      %a.button.submit{ :href => 'javascript:;' } 确认修改

app/views/settings/password.haml
.edit_info_form_panel
  = render 'shared/flash_notice'
  = form_tag '', :id => 'settingForm' do
    .blank
      %span.attr 当前密码：
      %input.text{ :type => 'password', :name => 'current_password' }
      %span.message 输入你当前的密码
    .blank
      %span.attr 新密码：
      %input.text{ :type => 'password', :name => 'new_password' }
      %span.message 输入新密码
    .blank
      %span.attr 确认新密码：
      %input.text{ :type => 'password', :name => 'new_password_confirmation' }
      %span.message 确认输入的新密码

    .buttons
      %a.button.submit{ :href => 'javascript:;' } 确认修改